FROM nvidia/cuda:11.8.0-runtime-ubuntu20.04

WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-opencv libgl1-mesa-glx \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]